# Generated by Django 5.2.1 on 2025-06-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icd_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código CIE')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='pacientes.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-date'],
            },
        ),
    ]
